### PR TITLE
Fixes Issue #695. Recovered File Day 14.

### PR DESCRIPTION
**Pull request by gurvirbaraich**
The file had wrong name in Day 14. Changed the name to its original name. From this `13_day_console_object_methods.md` to `14_day_error_handling.md`

### CODE REVIEW

**Review by fm852369741 — APPROVED** [review]
# Good Work

**Review by duytng93 — CHANGES_REQUESTED** [review]
..

**Comment by gurvirbaraich** [comment]
> ..

Why did you requested changes. You had to approve.

**Comment by duytng93** [comment]
> > duytng93
> 
> Why did you requested changes. You had to approve.

I am sorry. I really don't know how it works.

**Review by duytng93 — APPROVED** [review]

**Comment by gurvirbaraich** [comment]
> https://github.com/Asabeneh/30-Days-Of-JavaScript/pull/699#issuecomment-1436875344

```Request Changes``` means that you want that PR issuer should make changes to the amendments that he wants to make. Maybe because of typo, bug or anything else.

```Approve``` means you want these changes amended, which shows the owner or anyone with write access that these changes are valid and should be considered.

**Comment by duytng93** [comment]
Thank you so much. I have approved the change

**Pull request closed without merging**
